/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.devintest.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class DevintestApiException extends RuntimeException {
    public DevintestApiException(String message) {
        super(message);
    }

    public DevintestApiException(String message, Exception e) {
        super(message, e);
    }
}
