/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.devintest.api;

import com.devintest.api.core.ClientOptions;
import com.devintest.api.core.Suppliers;
import com.devintest.api.resources.imdb.AsyncImdbClient;
import java.util.function.Supplier;

public class AsyncDevintestApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncImdbClient> imdbClient;

    public AsyncDevintestApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.imdbClient = Suppliers.memoize(() -> new AsyncImdbClient(clientOptions));
    }

    public AsyncImdbClient imdb() {
        return this.imdbClient.get();
    }

    public static AsyncDevintestApiClientBuilder builder() {
        return new AsyncDevintestApiClientBuilder();
    }
}
