/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.devintest.api;

import com.devintest.api.core.ClientOptions;
import com.devintest.api.core.Suppliers;
import com.devintest.api.resources.imdb.ImdbClient;
import java.util.function.Supplier;

public class DevintestApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<ImdbClient> imdbClient;

    public DevintestApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.imdbClient = Suppliers.memoize(() -> new ImdbClient(clientOptions));
    }

    public ImdbClient imdb() {
        return this.imdbClient.get();
    }

    public static DevintestApiClientBuilder builder() {
        return new DevintestApiClientBuilder();
    }
}
